### PR TITLE
Add a new Pulp image using RHEL Universal Base Image

### PR DESCRIPTION
**Pull request by decko**
[noissue]

### CODE REVIEW

**Comment by bmbouter** [comment]
I think we need an image name that identifies the plugin in it (since we'll have several that are pulp ubi based). Here are two ideas:

* pulp-rpm-ubi
* pulp-content-sources
* your idea here

**Comment by bmbouter** [comment]
It's unclear to me if we'll be adding in pulp_ostree or not into this image, so maybe calling it `pulp-content-sources` would be good? Or if we do make it `pulp-rpm-ubi` we can later rename it to `pulp-rpm-ostree-ubi` would be fine too.

**Comment by decko** [comment]
> I think we need an image name that identifies the plugin in it (since we'll have several that are pulp ubi based). Here are two ideas:
> 
>     * pulp-rpm-ubi
> 
>     * pulp-content-sources
> 
>     * your idea here

What about `pulp-content-source-{plugin_name}`. It would sound strange if we use `pulp-content-source-rpm-ostree`???

**Comment by bmbouter** [comment]
What about `pulp-rpm-ubi` and we can change the name later?

**Review by dkliban — APPROVED** [review]

**Comment by dralley** [comment]
@bmbouter @decko Do we have any plans to support `ubi-minimal` as an install base?

**Comment by bmbouter** [comment]
> @bmbouter @decko Do we have any plans to support `ubi-minimal` as an install base?

There isn't a plan to build+publish these images as official pulp images, but the container file sources will be available in the source tree only if users want to adapt/adopt those. I don't perceive any community motivation to have a different base OS than centos, but if users wanted that we could consider building/supporting it.

**Comment by bmbouter** [comment]
BTW, this was actually moved here https://github.com/pulp/pulp-clowder-deployments/pull/5

**Comment by decko** [comment]
Closed since we moved it to `pulp/pulp-clowder-deployments`.

**Pull request closed without merging**
