### PR TITLE
Make the number of pulp_workers configurable

### LINKED ISSUE #225: Raise number of task workers to N + 1 number of parallel test runners.
The parallel test runner section of the CI is getting saturated by the number of task workers since most tests require a task to perform some work. @dkliban says the parallel test section uses 8 runners, so 9 task workers should be a good spot to start. One issue could be the container running OOM from having to many simultaneous tasks running, if so we can scale back from there.

### PR DESCRIPTION
**Pull request by mikedep333**
via the environment variable PULP_WORKERS.

fixes: #225

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by mdellweg** [comment]
Would it be possible to have a single s6-service to manage N workers?
Looks like we are trying to mimic the systemd "@" syntax with complicated hackery.

**Comment by mikedep333** [comment]
> Would it be possible to have a single s6-service to manage N workers? Looks like we are trying to mimic the systemd "@" syntax with complicated hackery.

The design of s6 is to have a (lightweight) [s6-supervise](s6-supervise) parent process per service. It restarts the service if it fails.

For this reason, it is either against the design or would break the service supervision to do that.

**Review by mdellweg — APPROVED** [review]
ME sad, because this looks really complicated. But if that's the way to do it...

**Comment by mikedep333** [comment]
> ME sad, because this looks really complicated. But if that's the way to do it...

Yeah, I know. This was annoyingly complicated to implement.

**Comment by mikedep333** [comment]
Note to self: Current problems with implementation

1. The output. Why is it being run twice? And the directory path is wrong (...uncompiled/s6-rc.d/type):
```
s6-rc: info: service postgres-prepare successfully started
s6-rc: info: service add-workers: starting
s6-rc: info: service pulpcore-worker@2: starting
s6-rc: info: service pulpcore-worker@1: starting
s6-rc: info: service pulpcore-content: starting
s6-rc: info: service pulpcore-api: starting
s6-rc: info: service pulpcore-worker@2 successfully started
s6-rc: info: service pulpcore-worker@1 successfully started
s6-rc: info: service pulpcore-content successfully started
Calling /etc/init/add-workers
s6-rc: info: service pulpcore-api successfully started
s6-rc: info: service nginx: starting
Checking for database migrations
Checking for database migrations
Checking for database migrations
Checking for database migrations
s6-rc: info: service nginx successfully started
[oneshot] add-workers: Adding workers 3 through 4
[oneshot] add-workers: Workers will be added shortly after the boot finishes
s6-rc: info: service add-workers successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[root@80f40f55ad58 /]# Calling /etc/init/add-workers
[oneshot] add-workers: Adding workers 3 through 4
rm: cannot remove '/tmp/1663353075_uncompiled/*/dependencies.d/base': No such file or directory
s6-rc-compile: fatal: unable to read /tmp/1663353075_uncompiled/s6-rc.d/type: No such file or directory
[oneshot] add-workers: Workers will be added shortly after the boot finishes
s6-rc: fatal: unable to take locks: Resource busy
s6-rc: fatal: unable to take locks: Resource busy
s6-rc-update: fatal: unable to rollback /run/s6-rc/compiled/servicedirs/s6rc-oneshot-runner into /run/s6-rc:s6-rc-update:kjlpLf/servicedirs/s6rc-oneshot-runner: No such file or directory
s6-rc: fatal: unable to take locks: No such file or directory
s6-rc: fatal: unable to take locks: No such file or directory
```
2. Addtl workers are not actually starting:
```
root          24       1  0 18:30 ?        00:00:00 s6-supervise pulpcore-worker@1
root          25       1  0 18:30 ?        00:00:00 s6-supervise pulpcore-worker@2
root         158      25  2 18:31 ?        00:00:05 /usr/bin/python3.8 /usr/local/bin/pulpcore-worker
root         159      24  2 18:31 ?        00:00:06 /usr/bin/python3.8 /usr/local/bin/pulpcore-worker
root         252       1  0 18:31 ?        00:00:00 s6-supervise pulpcore-worker@3
root         253       1  0 18:31 ?        00:00:00 s6-supervise pulpcore-worker@4
```

**Pull request merged**
