### PR TITLE
Support gunicorn worker recycling

### PR DESCRIPTION
**Pull request by markafarrell**
Currently the memory usage of the multi-process container increases over time the majority contributor is the gunicorn workers for  pulpcore-api

The suggested fix for these type of issues seems to be to enable worker recycling. 

pulp/pulpcore/issues/2250

The suggested solution of editing `gunicorn.conf.py`, however, does not work (I think due to how s6-overlay works)

This changes adds some additional environment variables that can be use to configure gunicorn worker recycling for both pulpcore-api and pulpcore-content

### CODE REVIEW

**Review by mikedep333 — APPROVED** [review]
Awesome, thank you so much!

**Review by mikedep333 — APPROVED** [review]

**Comment by mikedep333** [comment]
@markafarrell Lint is failing.

You need a file CHANGES/576.feature on your commit that says "fixes #576"

**Comment by markafarrell** [comment]
> @markafarrell Lint is failing.
> 
> You need a file CHANGES/576.feature on your commit that says "fixes #576"

Fixed.... hopefully

**Comment by markafarrell** [comment]
CI is failing due to:

``` 
 The conflict is caused by:
    The user requested pulpcore 3.45.0.dev0 (from git+https://github.com/pulp/pulpcore.git#egg=pulpcore)
    pulp-ansible 0.22.0.dev0 depends on pulpcore<3.55 and >=3.40.0
    pulp-certguard 1.8.0.dev0 depends on pulpcore<3.45 and >=3.28.0
```
`pulp-certguard`'s `pulpcore` version restrictions need to be expanded

https://github.com/pulp/pulp-certguard/issues/352
https://github.com/pulp/pulp-certguard/pull/353

**Comment by markafarrell** [comment]
```
 pulp-oci-images CI / app-images (stable, pulp, pulp-web, pulpcore) (pull_request) Failing after 19m
```
This also appears to be failing on latest

https://github.com/pulp/pulp-oci-images/issues/579

**Comment by mikedep333** [comment]
@markafarrell Yeah, we'll fix both of those 2 issues soon.

Thank you!

**Comment by mdellweg** [comment]
This change is incompatible with (at least) pulpcore 3.34. I'm inclined to revert it.

**Comment by mdellweg** [comment]
Nightlies are failing for some days now. We need to revert this and find a better solution.
https://github.com/pulp/pulp_gem/actions/runs/7620480802/job/20755309808#step:10:558

**Pull request merged**
