### PR TITLE
3.21: Update CentOS 8 containers for the distro's EOL

### PR DESCRIPTION
**Pull request by mikedep333**
Fixes: #634

### CODE REVIEW

**Review by decko — DISMISSED** [review]

**Review by dralley — APPROVED** [review]

**Comment by dralley** [comment]
would it be feasible to switch to alma instead of using the vault repos?

**Comment by mikedep333** [comment]
> would it be feasible to switch to alma instead of using the vault repos?

It would probably be more work in the short-term, but help us long-term.

**Comment by mikedep333** [comment]
@decko The tests are not passing anyway on nightly CI. How about we just merge this or close this?

**Review by lubosmj — APPROVED** [review]

**Comment by lubosmj** [comment]
If the release image runner is failing, how can we ensure that this change will be propagated to the upstream? I wonder if we should at least temporarily merge this instead: https://github.com/pulp/plugin_template/pull/873.

**Comment by decko** [comment]
> If the release image runner is failing, how can we ensure that this change will be propagated to the upstream? I wonder if we should at least temporarily merge this instead: [pulp/plugin_template#873](https://github.com/pulp/plugin_template/pull/873).

What do you think @mikedep333? 
Maybe some coordination on the #pulp-deployers channel to understand why some checks are failing and which PR should be prioritized.

**Comment by mikedep333** [comment]
@lubosmj @decko The 3.21 branch has been failing to publish for the last 6 months. Are you sure you guys actually use it?

https://quay.io/repository/pulp/pulp-ci-centos?tab=tags

**Comment by lubosmj** [comment]
We are using the `latest` tag. Which was uploaded 4 months ago:
image

**Pull request merged**
