### PR TITLE
Https template

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Comment by fao89** [comment]
Breaking because of click, waiting on pulpcore releases

**Comment by fao89** [comment]
I used the commit from: https://github.com/pulp/pulp-oci-images/pull/73
and started a Makefile and images template.
This is the only thing blocking https PRs

I think we can merge https://github.com/pulp/pulp-oci-images/pull/73 rebase this PR, and address the comments here
Once https://github.com/pulp/pulp-oci-images/pull/73 is merged, we can merge https://github.com/pulp/plugin_template/pull/379 and reapply it on the plugins

**Comment by fao89** [comment]
> I used the commit from: #73
> and started a Makefile and images template.
> This is the only thing blocking https PRs
> 
> I think we can merge #73 rebase this PR, and address the comments here
> Once #73 is merged, we can merge [pulp/plugin_template#379](https://github.com/pulp/plugin_template/pull/379) and reapply it on the plugins

@pulp/continuous-integration can I get a review?

**Comment by mdellweg** [comment]
I think, this is great. I'm not really sure if the very thin Makefile layer is adding any value here, but maybe calling ansible-playbook by hand _is_ tedious.
The one thing i really need in this pr is to add the generated files to `.gitignore`.

**Pull request closed without merging**
