### PR TITLE
Add Containerfile for Galaxy

### PR DESCRIPTION
**Pull request by mdellweg**
fixes #6713
https://pulp.plan.io/issues/6713

### CODE REVIEW

**Comment by mdellweg** [comment]
With this new Containerfile i was able to build and run a container that provides the galaxy login screen. @chouseknecht

How do we want to deliver this? (In a separate image, or always installed in the common image?) @bmbouter, @dkliban 

Commands to reproduce:
```
buildah bud -f galaxy_ng/Containerfile -t pulp_galaxy_ng .
podman run --publish 8080:80 --device /dev/fuse --name pulp --volume ./settings:/etc/pulp pulp_galaxy_ng
```

**Comment by chouseknecht** [comment]
@mdellweg having a separate image for galaxy_ng would be pretty sweet!

**Comment by bmbouter** [comment]
Thanks @chouseknecht 

@mdellweg so that would be a container that ships: galaxy_ng, pulp_ansible, and pulp_contianer. Both container and ansible are dependencies of galaxy_ng. Would you be able to create that? How hard is it to auto-build-ship one of those too?

**Comment by mdellweg** [comment]
This is exectly what the image contains. Buildshipping it is as hard as finding a proper name for it. Any suggests?

**Comment by sivel** [comment]
I've tested this by switching to the `pulp-galaxy-ng` image in the ansible/ansible integration tests and it is passing.  See https://github.com/ansible/ansible/pull/70303

**Comment by sivel** [comment]
I think we are all good with `pulp/pulp-galaxy-ng`.

**Comment by bmbouter** [comment]
I agree, let's find a way to merge this. @mdellweg what do we need to do to merge this? I see one of the quality checks is still failing.

**Comment by mdellweg** [comment]
I think, the build failure is due to pip19, so needs a rebase.

**Pull request merged**
