### PR TITLE
Enable multi-arch builds again

### LINKED ISSUE #366: Build multiplatform images
https://docs.docker.com/build/building/multi-platform/

### PR DESCRIPTION
**Pull request by StopMotionCuber**
This is the same as for #367 and should fix #366. For some reason that commit got reverted and I'm not sure why.

### CODE REVIEW

**Comment by StopMotionCuber** [comment]
bump

**Comment by mdellweg** [comment]
https://github.com/pulp/pulp-oci-images/pull/369#issue-1448605798

`it is breaking pulp-operator ci` is the only reason I can find, but it's a serious one. Can someone verify if it still holds true?

**Comment by StopMotionCuber** [comment]
Bumping this again, would still like to see mult-arch builds working on here.
It's frustrating to not see any activity here, especially with `arm64` gaining more and more mainstream attention and the whole software stack being capable of execution with `arm64`

**Review by mikedep333 — APPROVED** [review]

**Comment by mikedep333** [comment]
@StopMotionCuber Sorry for the delay. I was out the month of September and this fell through the cracks.

Merging now!

**Comment by himdel** [comment]
Building oci-env fails after this change... (on amd64)

```
Status: Downloaded newer image for ghcr.io/pulp/pulp-ci-centos:latest
 ---> 9fdc7e498755
Step 3/15 : ENV S6_KEEP_ENV=1
 ---> [Warning] The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 100673aa7dcd
Removing intermediate container 100673aa7dcd
 ---> 77987c9ffd49
Step 4/15 : ENV XDG_CONFIG_HOME=/opt/settings
 ---> [Warning] The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 7c8caa12cf3a
Removing intermediate container 7c8caa12cf3a
 ---> d822d82947b5
Step 5/15 : COPY dev_requirements.txt /dev_requirements.txt
 ---> 6559fa3e398a
Step 6/15 : COPY switch_python /usr/bin/switch_python
 ---> f0558bbd1071
Step 7/15 : ARG PYTHON_VERSION=3.8
 ---> [Warning] The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 0b193a720720
Removing intermediate container 0b193a720720
 ---> 3d49444ee46a
Step 8/15 : RUN switch_python "$PYTHON_VERSION"
 ---> [Warning] The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 8e9ae5f2f9c8
exec /bin/sh: exec format error
The command '/bin/sh -c switch_python "$PYTHON_VERSION"' returned a non-zero code: 1
ERROR: Service '_base' failed to build : Build failed
TIME 0:47.71
```

(also, https://github.com/ansible/ansible-hub-ui/actions/runs/6924023217/job/18832694190?pr=4531#step:9:223)


(This looks quite close to the errors seen in https://github.com/pulp/oci_env/pull/124, referencing https://github.com/pulp/pulp-oci-images/pull/369 ... might be why this was previously reverted? Should we do so again?)

**Comment by StopMotionCuber** [comment]
I'd favor not directly closing it, but rather solving the root cause of that issue

**Comment by StopMotionCuber** [comment]
I'm currently emulating the building steps manually on my workstation (takes quite a while with `qemu` and the way this repo is setup). I guess something goes wrong with pushing the containers.

**Comment by himdel** [comment]
I was looking for some sort of override that would be forcing oci-env to build a non-default arch, but I *think* what's happening is, the multi-archness of the image is infectious and causes any images built from it to also try building for all the archs, as opposed to just the current one.

After pruning everything, setting `export DOCKER_DEFAULT_PLATFORM=linux/amd64`, the build doesn't fail.
(I have yet to find a workaround that doesn't require users to know their platform, and not sure how that interacts with docker machine on macosx yet.)

**Comment by StopMotionCuber** [comment]
@himdel I'm not completely sure about your investigation.

What I've discovered so far was that no multi-arch manifest is pushed to the registry and I'm not sure which architecture is pushed to the registry or whether that is random (which might lead to some weird effects). Unfortunately with `podman` the multi-arch build is harder than what is there with `docker buildx`.

Anyway, a followup is ready in #562, which does the manifest stuff properly

**Pull request merged**
