### PR TITLE
Remove nightly scenario and galaxy images

### PR DESCRIPTION
**Pull request by gerrod3**
The nightly images are still built & published in our nightly release run, but they will no longer be tested. Since we can release at any time and since the nightly images don't have any other plugins, I feel we are not getting much from testing them.

### CODE REVIEW

**Review by decko — APPROVED** [review]

**Comment by pcuci** [comment]
Hi @gerrod3 - I was following the docs on how to use the galaxy images, but now they're gone with https://github.com/pulp/pulp-oci-images/pull/679/commits/0d12a184f6ad46ca24a7f700094b8c8acdba2288

Could you point me to the relevant documentation to bootstrap a local galaxy stack with compose please?

https://github.com/ansible/galaxy_ng points to the main Pulp docs page, then I'm lost, not sure what to read up on :-)

**Comment by gerrod3** [comment]
@pcuci Sorry about that, we will still be publishing the galaxy images for 4.8 & 4.9, (and potentially 4.10 when it is available on PyPI, our 3.49 branch can publish them), but going forward afterwards we won't be publishing any newer versions. Let me open a new docs PR for users who still want to use the old images, but in the meantime you can use the docs still on the old branch: https://github.com/pulp/pulp-oci-images/blob/3.49/staging_docs/admin/learn/single-process-images.md#galaxy-minimal

**Comment by pcuci** [comment]
_> users who still want to use the old images_

I can switch to the "new way", I just don't know where to look in the docs?

Will you still support Galaxy NG? @gerrod3 

Is this it? https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/usage_guide/installation/

**Comment by gerrod3** [comment]
> Will you still support Galaxy NG? @gerrod3

Yes, we will continue to support the existing 4.8 & 4.9 images (and probably 4.10 once it is available). The main change is the latest branches will not be building/testing newer galaxy versions. Pulp releases at a much faster cadence then galaxy-ng, so this will help reduce the amount work needed to maintain our CI.

> Is this it? https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/usage_guide/installation/

Yes, also the galaxy instructions for compose are still up on our docs as well: https://pulpproject.org/pulp-oci-images/docs/admin/reference/available-images/single-process-images/#galaxy-minimal. I not going to remove them, just update them on which galaxy-ng versions will be available in our images going forward.

**Pull request merged**
