### PR TITLE
Adds pulp-python

### PR DESCRIPTION
**Pull request by fao89**
[noissue]

### CODE REVIEW

**Review by mdellweg — COMMENTED** [review]
Is this limiting our ability to build images for older versions of pulp?

@daviddavis do you know?

**Comment by daviddavis** [comment]
@mdellweg indeed, that will be [an issue](https://github.com/pulp/pulp_python/blob/34420ba1aa486290b731cedf927a5bf54e5c8965/requirements.txt#L1). Is there a way to exclude pulp_python if pulpcore is < 3.9?

**Comment by daviddavis** [comment]
@mdellweg I think at one point you mentioned branching pulp-oci-images? That might be an option.

**Comment by daviddavis** [comment]
Here's what I am thinking: 
* Create branches 3.7, 3.8, 3.9, and latest (and ditch master). 
* Pull this change to add pulp_python into latest and 3.9.
* The nightly job will run against latest and publish latest. 
* The manual job will take a branch name and publish it using the branch name as the tag

WDYT? cc @dkliban

**Comment by dkliban** [comment]
That sounds good to me @daviddavis

**Comment by daviddavis** [comment]
Ok, here is the change to the workflow: https://github.com/pulp/pulp-oci-images/pull/41

Once we merge that and branch, I think we can merge this change to add pulp_python.

**Review by daviddavis — APPROVED** [review]

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
