### PR TITLE
Removes resource manager from single container

### PR DESCRIPTION
**Pull request by bmbouter**
The resource manager no longer able to be run in the upcoming version of
Pulp.

### CODE REVIEW

**Comment by mdellweg** [comment]
Do we already use a versioned variant of the `pulp_ci_centos` image in the older release branches? If not, this will break everything still depending on the resource-manager running.

**Comment by bmbouter** [comment]
I thought this over some, and I think we should merge this even if later we'll have to put in more work to release older branches. Mainly I just think we need to get this ready for the 3.17 release.

**Comment by mdellweg** [comment]
> I thought this over some, and I think we should merge this even if later we'll have to put in more work to release older branches. Mainly I just think we need to get this ready for the 3.17 release.

We need to be able to produce z stream releases at any point in time. So i think we need a strategy.

For now, we can extend the version checking strategy and only start the resource-manager for pulpcore < 3.16.
I know ite in readline is a pain.

**Comment by bmbouter** [comment]
I'm closing this PR in favor of https://github.com/pulp/pulp-oci-images/pull/136

**Pull request closed without merging**
